name: Lint and test PRs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter format --set-exit-if-changed lib test example/lib example/integration_test
      - run: flutter analyze lib test example/lib example/integration_test
      - run: flutter test
